#include <kernel/interrupts.h>
#include <stdio.h>


extern void ignoreInterruptRequest();
extern void handleInterruptRequest00();
extern void handleInterruptRequest01();
extern void handleInterruptRequest02();
extern void handleInterruptRequest03();
extern void handleInterruptRequest04();
extern void handleInterruptRequest05();
extern void handleInterruptRequest06();
extern void handleInterruptRequest07();
extern void handleInterruptRequest08();
extern void handleInterruptRequest09();
extern void handleInterruptRequest10();
extern void handleInterruptRequest11();
extern void handleInterruptRequest12();
extern void handleInterruptRequest13();
extern void handleInterruptRequest14();
extern void handleInterruptRequest15();
extern void handleInterruptRequest16();
extern void handleInterruptRequest17();
extern void handleInterruptRequest18();
extern void handleInterruptRequest19();
extern void handleInterruptRequest20();
extern void handleInterruptRequest21();
extern void handleInterruptRequest22();
extern void handleInterruptRequest23();
extern void handleInterruptRequest24();
extern void handleInterruptRequest25();
extern void handleInterruptRequest26();
extern void handleInterruptRequest27();
extern void handleInterruptRequest28();
extern void handleInterruptRequest29();
extern void handleInterruptRequest30();
extern void handleInterruptRequest31();
extern void handleInterruptRequest32();
extern void handleInterruptRequest33();
extern void handleInterruptRequest34();
extern void handleInterruptRequest35();
extern void handleInterruptRequest36();
extern void handleInterruptRequest37();
extern void handleInterruptRequest38();
extern void handleInterruptRequest39();
extern void handleInterruptRequest40();
extern void handleInterruptRequest41();
extern void handleInterruptRequest42();
extern void handleInterruptRequest43();
extern void handleInterruptRequest44();
extern void handleInterruptRequest45();
extern void handleInterruptRequest46();
extern void handleInterruptRequest47();
extern void handleInterruptRequest48();
extern void handleInterruptRequest49();
extern void handleInterruptRequest50();
extern void handleInterruptRequest51();
extern void handleInterruptRequest52();
extern void handleInterruptRequest53();
extern void handleInterruptRequest54();
extern void handleInterruptRequest55();
extern void handleInterruptRequest56();
extern void handleInterruptRequest57();
extern void handleInterruptRequest58();
extern void handleInterruptRequest59();
extern void handleInterruptRequest60();
extern void handleInterruptRequest61();
extern void handleInterruptRequest62();
extern void handleInterruptRequest63();
extern void handleInterruptRequest64();
extern void handleInterruptRequest65();
extern void handleInterruptRequest66();
extern void handleInterruptRequest67();
extern void handleInterruptRequest68();
extern void handleInterruptRequest69();
extern void handleInterruptRequest70();
extern void handleInterruptRequest71();
extern void handleInterruptRequest72();
extern void handleInterruptRequest73();
extern void handleInterruptRequest74();
extern void handleInterruptRequest75();
extern void handleInterruptRequest76();
extern void handleInterruptRequest77();
extern void handleInterruptRequest78();
extern void handleInterruptRequest79();
extern void handleInterruptRequest80();
extern void handleInterruptRequest81();
extern void handleInterruptRequest82();
extern void handleInterruptRequest83();
extern void handleInterruptRequest84();
extern void handleInterruptRequest85();
extern void handleInterruptRequest86();
extern void handleInterruptRequest87();
extern void handleInterruptRequest88();
extern void handleInterruptRequest89();
extern void handleInterruptRequest90();
extern void handleInterruptRequest91();
extern void handleInterruptRequest92();
extern void handleInterruptRequest93();
extern void handleInterruptRequest94();
extern void handleInterruptRequest95();
extern void handleInterruptRequest96();
extern void handleInterruptRequest97();
extern void handleInterruptRequest98();
extern void handleInterruptRequest99();
extern void handleInterruptRequest100();
extern void handleInterruptRequest101();
extern void handleInterruptRequest102();
extern void handleInterruptRequest103();
extern void handleInterruptRequest104();
extern void handleInterruptRequest105();
extern void handleInterruptRequest106();
extern void handleInterruptRequest107();
extern void handleInterruptRequest108();
extern void handleInterruptRequest109();
extern void handleInterruptRequest110();
extern void handleInterruptRequest111();
extern void handleInterruptRequest112();
extern void handleInterruptRequest113();
extern void handleInterruptRequest114();
extern void handleInterruptRequest115();
extern void handleInterruptRequest116();
extern void handleInterruptRequest117();
extern void handleInterruptRequest118();
extern void handleInterruptRequest119();
extern void handleInterruptRequest120();
extern void handleInterruptRequest121();
extern void handleInterruptRequest122();
extern void handleInterruptRequest123();
extern void handleInterruptRequest124();
extern void handleInterruptRequest125();
extern void handleInterruptRequest126();
extern void handleInterruptRequest127();
extern void handleInterruptRequest128();
extern void handleInterruptRequest129();
extern void handleInterruptRequest130();
extern void handleInterruptRequest131();
extern void handleInterruptRequest132();
extern void handleInterruptRequest133();
extern void handleInterruptRequest134();
extern void handleInterruptRequest135();
extern void handleInterruptRequest136();
extern void handleInterruptRequest137();
extern void handleInterruptRequest138();
extern void handleInterruptRequest139();
extern void handleInterruptRequest140();
extern void handleInterruptRequest141();
extern void handleInterruptRequest142();
extern void handleInterruptRequest143();
extern void handleInterruptRequest144();
extern void handleInterruptRequest145();
extern void handleInterruptRequest146();
extern void handleInterruptRequest147();
extern void handleInterruptRequest148();
extern void handleInterruptRequest149();
extern void handleInterruptRequest150();
extern void handleInterruptRequest151();
extern void handleInterruptRequest152();
extern void handleInterruptRequest153();
extern void handleInterruptRequest154();
extern void handleInterruptRequest155();
extern void handleInterruptRequest156();
extern void handleInterruptRequest157();
extern void handleInterruptRequest158();
extern void handleInterruptRequest159();
extern void handleInterruptRequest160();
extern void handleInterruptRequest161();
extern void handleInterruptRequest162();
extern void handleInterruptRequest163();
extern void handleInterruptRequest164();
extern void handleInterruptRequest165();
extern void handleInterruptRequest166();
extern void handleInterruptRequest167();
extern void handleInterruptRequest168();
extern void handleInterruptRequest169();
extern void handleInterruptRequest170();
extern void handleInterruptRequest171();
extern void handleInterruptRequest172();
extern void handleInterruptRequest173();
extern void handleInterruptRequest174();
extern void handleInterruptRequest175();
extern void handleInterruptRequest176();
extern void handleInterruptRequest177();
extern void handleInterruptRequest178();
extern void handleInterruptRequest179();
extern void handleInterruptRequest180();
extern void handleInterruptRequest181();
extern void handleInterruptRequest182();
extern void handleInterruptRequest183();
extern void handleInterruptRequest184();
extern void handleInterruptRequest185();
extern void handleInterruptRequest186();
extern void handleInterruptRequest187();
extern void handleInterruptRequest188();
extern void handleInterruptRequest189();
extern void handleInterruptRequest190();
extern void handleInterruptRequest191();
extern void handleInterruptRequest192();
extern void handleInterruptRequest193();
extern void handleInterruptRequest194();
extern void handleInterruptRequest195();
extern void handleInterruptRequest196();
extern void handleInterruptRequest197();
extern void handleInterruptRequest198();
extern void handleInterruptRequest199();
extern void handleInterruptRequest200();
extern void handleInterruptRequest201();
extern void handleInterruptRequest202();
extern void handleInterruptRequest203();
extern void handleInterruptRequest204();
extern void handleInterruptRequest205();
extern void handleInterruptRequest206();
extern void handleInterruptRequest207();
extern void handleInterruptRequest208();
extern void handleInterruptRequest209();
extern void handleInterruptRequest210();
extern void handleInterruptRequest211();
extern void handleInterruptRequest212();
extern void handleInterruptRequest213();
extern void handleInterruptRequest214();
extern void handleInterruptRequest215();
extern void handleInterruptRequest216();
extern void handleInterruptRequest217();
extern void handleInterruptRequest218();
extern void handleInterruptRequest219();
extern void handleInterruptRequest220();
extern void handleInterruptRequest221();
extern void handleInterruptRequest222();
extern void handleInterruptRequest223();
extern void handleInterruptRequest224();
extern void handleInterruptRequest225();
extern void handleInterruptRequest226();
extern void handleInterruptRequest227();
extern void handleInterruptRequest228();
extern void handleInterruptRequest229();
extern void handleInterruptRequest230();
extern void handleInterruptRequest231();
extern void handleInterruptRequest232();
extern void handleInterruptRequest233();
extern void handleInterruptRequest234();
extern void handleInterruptRequest235();
extern void handleInterruptRequest236();
extern void handleInterruptRequest237();
extern void handleInterruptRequest238();
extern void handleInterruptRequest239();
extern void handleInterruptRequest240();
extern void handleInterruptRequest241();
extern void handleInterruptRequest242();
extern void handleInterruptRequest243();
extern void handleInterruptRequest244();
extern void handleInterruptRequest245();
extern void handleInterruptRequest246();
extern void handleInterruptRequest247();
extern void handleInterruptRequest248();
extern void handleInterruptRequest249();
extern void handleInterruptRequest250();
extern void handleInterruptRequest251();
extern void handleInterruptRequest252();
extern void handleInterruptRequest253();
extern void handleInterruptRequest254();
extern void handleInterruptRequest255();


InterruptManager::GateDescriptor InterruptManager::interruptDescriptorTable[256];
Pic InterruptManager::pic;

void InterruptManager::setInterruptDescriptorTableEntry(
		uint8_t interruptNumber, 
		uint16_t codeSegmentSelectorOffset,
		void (*handler)(void),
		uint8_t descriptorPrivilegeLevel,
		uint8_t descriptorType){

	const uint8_t IDT_DESC_PRESENT = 0x80;

	interruptDescriptorTable[interruptNumber].handlerAddressLowBits = ((uint32_t) handler) & 0xFFFF;
	interruptDescriptorTable[interruptNumber].handlerAddressHighBits = (((uint32_t) handler) >> 16) & 0xFFFF;
	interruptDescriptorTable[interruptNumber].gdt_codeSegmentSelector = codeSegmentSelectorOffset;
	interruptDescriptorTable[interruptNumber].access = IDT_DESC_PRESENT | descriptorType | ((descriptorPrivilegeLevel & 3) << 5);
	interruptDescriptorTable[interruptNumber].reserved = 0;
}

InterruptManager::InterruptManager(){
	uint16_t codeSegment = 1 << 3;
	const uint8_t IDT_INTERRUPT_GATE = 0xE;

	for(int i =0; i < 256; i++){
		setInterruptDescriptorTableEntry(i,codeSegment,ignoreInterruptRequest,0,IDT_INTERRUPT_GATE);
	}

	setInterruptDescriptorTableEntry(0, codeSegment, handleInterruptRequest00, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(1, codeSegment, handleInterruptRequest01, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(2, codeSegment, handleInterruptRequest02, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(3, codeSegment, handleInterruptRequest03, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(4, codeSegment, handleInterruptRequest04, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(5, codeSegment, handleInterruptRequest05, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(6, codeSegment, handleInterruptRequest06, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(7, codeSegment, handleInterruptRequest07, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(8, codeSegment, handleInterruptRequest08, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(9, codeSegment, handleInterruptRequest09, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(10, codeSegment, handleInterruptRequest10, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(11, codeSegment, handleInterruptRequest11, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(12, codeSegment, handleInterruptRequest12, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(13, codeSegment, handleInterruptRequest13, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(14, codeSegment, handleInterruptRequest14, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(15, codeSegment, handleInterruptRequest15, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(16, codeSegment, handleInterruptRequest16, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(17, codeSegment, handleInterruptRequest17, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(18, codeSegment, handleInterruptRequest18, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(19, codeSegment, handleInterruptRequest19, 0, IDT_INTERRUPT_GATE); 
	setInterruptDescriptorTableEntry(20, codeSegment, handleInterruptRequest20, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(21, codeSegment, handleInterruptRequest21, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(22, codeSegment, handleInterruptRequest22, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(23, codeSegment, handleInterruptRequest23, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(24, codeSegment, handleInterruptRequest24, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(25, codeSegment, handleInterruptRequest25, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(26, codeSegment, handleInterruptRequest26, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(27, codeSegment, handleInterruptRequest27, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(28, codeSegment, handleInterruptRequest28, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(29, codeSegment, handleInterruptRequest29, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(30, codeSegment, handleInterruptRequest30, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(31, codeSegment, handleInterruptRequest31, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(32, codeSegment, handleInterruptRequest32, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(33, codeSegment, handleInterruptRequest33, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(34, codeSegment, handleInterruptRequest34, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(35, codeSegment, handleInterruptRequest35, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(36, codeSegment, handleInterruptRequest36, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(37, codeSegment, handleInterruptRequest37, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(38, codeSegment, handleInterruptRequest38, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(39, codeSegment, handleInterruptRequest39, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(40, codeSegment, handleInterruptRequest40, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(41, codeSegment, handleInterruptRequest41, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(42, codeSegment, handleInterruptRequest42, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(43, codeSegment, handleInterruptRequest43, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(44, codeSegment, handleInterruptRequest44, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(45, codeSegment, handleInterruptRequest45, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(46, codeSegment, handleInterruptRequest46, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(47, codeSegment, handleInterruptRequest47, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(48, codeSegment, handleInterruptRequest48, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(49, codeSegment, handleInterruptRequest49, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(50, codeSegment, handleInterruptRequest50, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(51, codeSegment, handleInterruptRequest51, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(52, codeSegment, handleInterruptRequest52, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(53, codeSegment, handleInterruptRequest53, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(54, codeSegment, handleInterruptRequest54, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(55, codeSegment, handleInterruptRequest55, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(56, codeSegment, handleInterruptRequest56, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(57, codeSegment, handleInterruptRequest57, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(58, codeSegment, handleInterruptRequest58, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(59, codeSegment, handleInterruptRequest59, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(60, codeSegment, handleInterruptRequest60, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(61, codeSegment, handleInterruptRequest61, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(62, codeSegment, handleInterruptRequest62, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(63, codeSegment, handleInterruptRequest63, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(64, codeSegment, handleInterruptRequest64, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(65, codeSegment, handleInterruptRequest65, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(66, codeSegment, handleInterruptRequest66, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(67, codeSegment, handleInterruptRequest67, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(68, codeSegment, handleInterruptRequest68, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(69, codeSegment, handleInterruptRequest69, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(70, codeSegment, handleInterruptRequest70, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(71, codeSegment, handleInterruptRequest71, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(72, codeSegment, handleInterruptRequest72, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(73, codeSegment, handleInterruptRequest73, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(74, codeSegment, handleInterruptRequest74, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(75, codeSegment, handleInterruptRequest75, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(76, codeSegment, handleInterruptRequest76, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(77, codeSegment, handleInterruptRequest77, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(78, codeSegment, handleInterruptRequest78, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(79, codeSegment, handleInterruptRequest79, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(80, codeSegment, handleInterruptRequest80, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(81, codeSegment, handleInterruptRequest81, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(82, codeSegment, handleInterruptRequest82, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(83, codeSegment, handleInterruptRequest83, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(84, codeSegment, handleInterruptRequest84, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(85, codeSegment, handleInterruptRequest85, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(86, codeSegment, handleInterruptRequest86, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(87, codeSegment, handleInterruptRequest87, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(88, codeSegment, handleInterruptRequest88, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(80, codeSegment, handleInterruptRequest89, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(90, codeSegment, handleInterruptRequest90, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(91, codeSegment, handleInterruptRequest91, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(92, codeSegment, handleInterruptRequest92, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(93, codeSegment, handleInterruptRequest93, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(94, codeSegment, handleInterruptRequest94, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(95, codeSegment, handleInterruptRequest95, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(96, codeSegment, handleInterruptRequest96, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(97, codeSegment, handleInterruptRequest97, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(98, codeSegment, handleInterruptRequest98, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(99, codeSegment, handleInterruptRequest99, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(100, codeSegment, handleInterruptRequest100, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(101, codeSegment, handleInterruptRequest101, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(102, codeSegment, handleInterruptRequest102, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(103, codeSegment, handleInterruptRequest103, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(104, codeSegment, handleInterruptRequest104, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(105, codeSegment, handleInterruptRequest105, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(106, codeSegment, handleInterruptRequest106, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(107, codeSegment, handleInterruptRequest107, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(108, codeSegment, handleInterruptRequest108, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(109, codeSegment, handleInterruptRequest109, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(110, codeSegment, handleInterruptRequest110, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(111, codeSegment, handleInterruptRequest111, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(112, codeSegment, handleInterruptRequest112, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(113, codeSegment, handleInterruptRequest113, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(114, codeSegment, handleInterruptRequest114, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(115, codeSegment, handleInterruptRequest115, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(116, codeSegment, handleInterruptRequest116, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(117, codeSegment, handleInterruptRequest117, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(118, codeSegment, handleInterruptRequest118, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(119, codeSegment, handleInterruptRequest119, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(120, codeSegment, handleInterruptRequest120, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(121, codeSegment, handleInterruptRequest121, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(122, codeSegment, handleInterruptRequest122, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(123, codeSegment, handleInterruptRequest123, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(124, codeSegment, handleInterruptRequest124, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(125, codeSegment, handleInterruptRequest125, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(126, codeSegment, handleInterruptRequest126, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(127, codeSegment, handleInterruptRequest127, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(128, codeSegment, handleInterruptRequest128, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(129, codeSegment, handleInterruptRequest129, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(130, codeSegment, handleInterruptRequest130, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(131, codeSegment, handleInterruptRequest131, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(132, codeSegment, handleInterruptRequest132, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(133, codeSegment, handleInterruptRequest133, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(134, codeSegment, handleInterruptRequest134, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(135, codeSegment, handleInterruptRequest135, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(136, codeSegment, handleInterruptRequest136, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(137, codeSegment, handleInterruptRequest137, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(138, codeSegment, handleInterruptRequest138, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(139, codeSegment, handleInterruptRequest139, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(140, codeSegment, handleInterruptRequest140, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(141, codeSegment, handleInterruptRequest141, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(142, codeSegment, handleInterruptRequest142, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(143, codeSegment, handleInterruptRequest143, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(144, codeSegment, handleInterruptRequest144, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(145, codeSegment, handleInterruptRequest145, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(146, codeSegment, handleInterruptRequest146, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(147, codeSegment, handleInterruptRequest147, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(148, codeSegment, handleInterruptRequest148, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(149, codeSegment, handleInterruptRequest149, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(150, codeSegment, handleInterruptRequest150, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(151, codeSegment, handleInterruptRequest151, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(152, codeSegment, handleInterruptRequest152, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(153, codeSegment, handleInterruptRequest153, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(154, codeSegment, handleInterruptRequest154, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(155, codeSegment, handleInterruptRequest155, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(156, codeSegment, handleInterruptRequest156, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(157, codeSegment, handleInterruptRequest157, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(158, codeSegment, handleInterruptRequest158, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(159, codeSegment, handleInterruptRequest159, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(160, codeSegment, handleInterruptRequest160, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(161, codeSegment, handleInterruptRequest161, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(162, codeSegment, handleInterruptRequest162, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(163, codeSegment, handleInterruptRequest163, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(164, codeSegment, handleInterruptRequest164, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(165, codeSegment, handleInterruptRequest165, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(166, codeSegment, handleInterruptRequest166, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(167, codeSegment, handleInterruptRequest167, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(168, codeSegment, handleInterruptRequest168, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(169, codeSegment, handleInterruptRequest169, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(170, codeSegment, handleInterruptRequest170, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(171, codeSegment, handleInterruptRequest171, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(172, codeSegment, handleInterruptRequest172, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(173, codeSegment, handleInterruptRequest173, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(174, codeSegment, handleInterruptRequest174, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(175, codeSegment, handleInterruptRequest175, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(176, codeSegment, handleInterruptRequest176, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(177, codeSegment, handleInterruptRequest177, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(178, codeSegment, handleInterruptRequest178, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(179, codeSegment, handleInterruptRequest179, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(180, codeSegment, handleInterruptRequest180, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(181, codeSegment, handleInterruptRequest181, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(182, codeSegment, handleInterruptRequest182, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(183, codeSegment, handleInterruptRequest183, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(184, codeSegment, handleInterruptRequest184, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(185, codeSegment, handleInterruptRequest185, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(186, codeSegment, handleInterruptRequest186, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(187, codeSegment, handleInterruptRequest187, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(188, codeSegment, handleInterruptRequest188, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(189, codeSegment, handleInterruptRequest189, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(190, codeSegment, handleInterruptRequest190, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(191, codeSegment, handleInterruptRequest191, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(192, codeSegment, handleInterruptRequest192, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(193, codeSegment, handleInterruptRequest193, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(194, codeSegment, handleInterruptRequest194, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(195, codeSegment, handleInterruptRequest195, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(196, codeSegment, handleInterruptRequest196, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(197, codeSegment, handleInterruptRequest197, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(198, codeSegment, handleInterruptRequest198, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(199, codeSegment, handleInterruptRequest199, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(200, codeSegment, handleInterruptRequest200, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(201, codeSegment, handleInterruptRequest201, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(202, codeSegment, handleInterruptRequest202, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(203, codeSegment, handleInterruptRequest203, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(204, codeSegment, handleInterruptRequest204, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(205, codeSegment, handleInterruptRequest205, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(206, codeSegment, handleInterruptRequest206, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(207, codeSegment, handleInterruptRequest207, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(208, codeSegment, handleInterruptRequest208, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(209, codeSegment, handleInterruptRequest209, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(210, codeSegment, handleInterruptRequest210, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(211, codeSegment, handleInterruptRequest211, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(212, codeSegment, handleInterruptRequest212, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(213, codeSegment, handleInterruptRequest213, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(214, codeSegment, handleInterruptRequest214, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(215, codeSegment, handleInterruptRequest215, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(216, codeSegment, handleInterruptRequest216, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(217, codeSegment, handleInterruptRequest217, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(218, codeSegment, handleInterruptRequest218, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(219, codeSegment, handleInterruptRequest219, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(220, codeSegment, handleInterruptRequest220, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(221, codeSegment, handleInterruptRequest221, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(222, codeSegment, handleInterruptRequest222, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(223, codeSegment, handleInterruptRequest223, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(224, codeSegment, handleInterruptRequest224, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(225, codeSegment, handleInterruptRequest225, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(226, codeSegment, handleInterruptRequest226, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(227, codeSegment, handleInterruptRequest227, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(228, codeSegment, handleInterruptRequest228, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(229, codeSegment, handleInterruptRequest229, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(230, codeSegment, handleInterruptRequest230, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(231, codeSegment, handleInterruptRequest231, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(232, codeSegment, handleInterruptRequest232, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(233, codeSegment, handleInterruptRequest233, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(234, codeSegment, handleInterruptRequest234, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(235, codeSegment, handleInterruptRequest235, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(236, codeSegment, handleInterruptRequest236, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(237, codeSegment, handleInterruptRequest237, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(238, codeSegment, handleInterruptRequest238, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(239, codeSegment, handleInterruptRequest239, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(240, codeSegment, handleInterruptRequest240, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(241, codeSegment, handleInterruptRequest241, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(242, codeSegment, handleInterruptRequest242, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(243, codeSegment, handleInterruptRequest243, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(244, codeSegment, handleInterruptRequest244, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(245, codeSegment, handleInterruptRequest245, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(246, codeSegment, handleInterruptRequest246, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(247, codeSegment, handleInterruptRequest247, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(248, codeSegment, handleInterruptRequest248, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(249, codeSegment, handleInterruptRequest249, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(250, codeSegment, handleInterruptRequest250, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(251, codeSegment, handleInterruptRequest251, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(252, codeSegment, handleInterruptRequest252, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(253, codeSegment, handleInterruptRequest253, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(254, codeSegment, handleInterruptRequest254, 0, IDT_INTERRUPT_GATE);
	setInterruptDescriptorTableEntry(255, codeSegment, handleInterruptRequest255, 0, IDT_INTERRUPT_GATE);

	InterruptDescriptorTablePointer idt_pointer;
	idt_pointer.size = (256 * 8) - 1;
	idt_pointer.base = (uint32_t)interruptDescriptorTable;
	asm volatile("lidt %0" : : "m" (idt_pointer));
}

InterruptManager::~InterruptManager(){

}

void InterruptManager::activate(){
	asm("sti");
}

void InterruptManager::ackInt(uint32_t num){
	if(num >= 20){
		pic.getSlaveCommand().write(0x20);
	}
	pic.getMasterCommand().write(0x20);

}

uint32_t InterruptManager::handleInterrupt(uint32_t esp){
	printf("INTERRUPT\n");
	ackInt(esp);
	return esp;
}